name: vision_aid
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  # firebase_ui_database: ^1.3.4
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4

  cupertino_icons: ^1.0.6

  google_maps_flutter: ^2.2.8
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  flutter_polyline_points: ^2.0.0

  font_awesome_flutter: ^10.4.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  http: ^1.0.0
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  image_picker: ^0.8.7+4
  form_field_validator: ^1.1.0
  android_intent_plus: ^3.1.9
  shimmer: ^2.0.0
  carousel_slider: ^4.1.1
  permission_handler: ^10.2.0
  intl: ^0.18.1
  polyline_do: ^0.1.0
  url_launcher: ^6.1.10
  socket_io_client: 1.0.2
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^14.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/
    - Assets/Logo/
    - Assets/svg/
